# Generated by Django 3.1.3 on 2020-11-09 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopcarts', '0002_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=models.DateTimeField(default=django.utils.timezone.now)),
        ),
    ]
