# Generated by Django 3.1.3 on 2020-11-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcarts', '0005_auto_20201109_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
