# Generated by Django 3.1.3 on 2020-11-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcarts', '0015_auto_20201110_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
    ]
