# Generated by Django 3.1.3 on 2020-11-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcarts', '0023_auto_20201112_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cartitem',
            new_name='cart',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
