# Generated by Django 3.1.3 on 2020-11-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcarts', '0027_auto_20201113_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='shopcarts.CartItem', to='shopcarts.Product'),
        ),
    ]
