# Generated by Django 3.1.3 on 2020-11-14 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopcarts', '0028_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='check_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopcarts.cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('na', 'None'), ('cancelled', 'Cancelled'), ('ordered', 'Ordered'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='na', max_length=20),
        ),
    ]
