# Generated by Django 3.1.3 on 2020-11-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcarts', '0030_cartitem_ordered_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='ordered_at',
        ),
    ]
