# Generated by Django 3.1.3 on 2020-11-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcarts', '0035_auto_20201115_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='ordered_at',
        ),
    ]
