# Generated by Django 3.1.3 on 2020-11-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcarts', '0042_auto_20201116_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='ordered_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='shopcarts.CartItem'),
        ),
    ]
