# Generated by Django 3.1.3 on 2020-11-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcarts', '0045_auto_20201118_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='shopcarts/media/'),
        ),
    ]
