# Generated by Django 3.1.3 on 2020-11-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcarts', '0049_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='shopcarts.CartItem'),
        ),
    ]
