# Generated by Django 3.1.3 on 2020-11-22 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcarts', '0062_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
