# Generated by Django 3.1.3 on 2020-11-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcarts', '0069_auto_20201126_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='check_order',
        ),
    ]
