# Generated by Django 3.1.3 on 2020-11-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcarts', '0071_auto_20201127_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='shopcarts.ProductOrder', to='shopcarts.Product'),
        ),
    ]
