# Generated by Django 3.1.3 on 2020-11-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcarts', '0072_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
